<template>
  <div class="placeholder-page">
    <div class="container">
      <span class="placeholder-icon">&#128202;</span>
      <h1>Dataset: {{ $route.params.pxd }}</h1>
      <p style="margin-bottom: 8px;">Collection: <strong>{{ $route.params.name }}</strong></p>
      <p>
        Dataset metadata, sample table, and download links will appear here
        once the collection data is generated by the quantms-portal pipeline.
      </p>
    </div>
  </div>
</template>
